In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv("D:/study/DATA SCIENCE/great learning/NLP/Project/blogtext.csv")

In [4]:
df.shape

(681284, 7)

In [8]:
df.head(10)

,id,gender,age,topic,sign,date,text
0,2059027,male,15,Student,Leo,"14,May,2004","Info has been found (+/- 100 pages,..."
1,2059027,male,15,Student,Leo,"13,May,2004",These are the team members: Drewe...
2,2059027,male,15,Student,Leo,"12,May,2004",In het kader van kernfusie op aarde...
3,2059027,male,15,Student,Leo,"12,May,2004",testing!!! testing!!!
4,3581210,male,33,InvestmentBanking,Aquarius,"11,June,2004",Thanks to Yahoo!'s Toolbar I can ...
5,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",I had an interesting conversation...
6,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",Somehow Coca-Cola has a way of su...
7,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004","If anything, Korea is a country o..."
8,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",Take a read of this news article ...
9,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",I surf the English news sites a l...

In [6]:
df= df.head(5000)

In [7]:
df.shape

(5000, 7)

In [9]:
df.drop('id', axis= 1, inplace= True)

In [10]:
import re

In [15]:
txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

In [16]:
x

In [17]:
txt = "The rain in Spain"
x = re.findall("ai", txt)
print(x)

['ai', 'ai']

In [18]:
txt = "The rain in Spain"
x = re.findall("Portugal", txt)
print(x)

[]

In [20]:
txt = "The rain in Spain"
x = re.search("T", txt)

print("The first white-space character is located in position:", x.start())

The first white-space character is located in position: 0

In [22]:
txt = "The rain in Spain"
x = re.split("\s", txt, 1)
print(x)

['The', 'rain in Spain']

In [24]:
txt = "The rain in Spain"
x = re.sub("\s", "9", txt, 2)
print(x)

The9rain9in Spain

In [47]:
import re
df.text = df.text.apply(lambda x: re.sub('[^A-Za-z]+', ' ', x))   # for selecting only the alphabets

# Convert text to lowercase
df.text = df.text.apply(lambda x: x.lower())

# Strip unwanted spaces
df.text = df.text.apply(lambda x: x.strip())

#took the help from the solutions

In [43]:
import nltk

In [44]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harshit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [45]:
from nltk.corpus import stopwords

In [46]:
stopwords

In [48]:
stopwords= set(stopwords.words('english'))          #took the help from solution

In [50]:
len(stopwords)        #there are 179 stopwords

179

In [54]:
df.text = df.text.apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords]))  #taken help from solution

In [55]:
df

,gender,age,topic,sign,date,text
0,male,15,Student,Leo,"14,May,2004",info found pages mb pdf files wait untill team...
1,male,15,Student,Leo,"13,May,2004",team members drewes van der laag urllink mail ...
2,male,15,Student,Leo,"12,May,2004",het kader van kernfusie op aarde maak je eigen...
3,male,15,Student,Leo,"12,May,2004",testing testing
4,male,33,InvestmentBanking,Aquarius,"11,June,2004",thanks yahoo toolbar capture urls popups means...
...,...,...,...,...,...,...
4995,female,17,indUnk,Scorpio,"27,August,2003",another one dreams last night except time leas...
4996,female,17,indUnk,Scorpio,"27,August,2003",mmm strawberry tea breakfast tomorrow think de...
4997,female,17,indUnk,Scorpio,"27,August,2003",yay new layout yeah know need get complicated ...
4998,female,17,indUnk,Scorpio,"26,August,2003",ok lied fed playing friday night underdog cons...
4999,female,17,indUnk,Scorpio,"26,August,2003",well today went church talked music director t...

In [56]:
df.drop('date', axis= 1, inplace= True)

In [57]:
df.shape

(5000, 5)

In [62]:
df['labels']= df.apply(lambda row: [row['gender'], str(row['age']), row['topic'], row['sign']], axis=1)

In [64]:
df.drop(['gender', 'age', 'sign', 'topic'], axis= 1, inplace= True)  #removing the individual columns after forming a cosolidated column

In [66]:
df.head()

,text,labels
0,info found pages mb pdf files wait untill team...,"[male, 15, Student, Leo]"
1,team members drewes van der laag urllink mail ...,"[male, 15, Student, Leo]"
2,het kader van kernfusie op aarde maak je eigen...,"[male, 15, Student, Leo]"
3,testing testing,"[male, 15, Student, Leo]"
4,thanks yahoo toolbar capture urls popups means...,"[male, 33, InvestmentBanking, Aquarius]"

In [67]:
#splitting the test and train data set 
X= df['text']
y= df['labels']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state= 1, test_size= 0.3)

In [68]:
from sklearn.feature_extraction.text import CountVectorizer

In [77]:
toNumeric=  CountVectorizer(binary= True, ngram_range=(1, 2))

In [78]:
toNumeric.fit(X_train)

CountVectorizer(binary=True, ngram_range=(1, 2))

In [79]:
dtm_train= toNumeric.transform(X_train)
dtm_test= toNumeric.transform(X_test)

In [80]:
dtm_train

<3500x238234 sparse matrix of type '<class 'numpy.int64'>'
	with 452767 stored elements in Compressed Sparse Row format>

In [81]:
dtm_test

<1500x238234 sparse matrix of type '<class 'numpy.int64'>'
	with 110189 stored elements in Compressed Sparse Row format>

In [ ]:
#creating dictionary of words 
dict= {}

In [82]:
toNumeric.get_feature_names()

['aa',
 'aa amazing',
 'aaa',
 'aaa come',
 'aaa someone',
 'aaa tow',
 'aaa travel',
 'aaaaaah',
 'aaaaaawwwwww',
 'aaaaaawwwwww gets',
 'aaaaack',
 'aaaaahhhh',
 'aaaaahhhh heath',
 'aaaah',
 'aaaah wisdom',
 'aaaahh',
 'aaagh',
 'aaagh pero',
 'aaahhhh',
 'aaahhhh diva',
 'aaarrrggghhhhhhhhgggghhhhhh',
 'aaarrrggghhhhhhhhgggghhhhhh dropped',
 'aaja',
 'aaja unity',
 'aal',
 'aal eliminate',
 'aal powerful',
 'aal rather',
 'aarde',
 'aarde maak',
 'aargh',
 'aargh told',
 'aaron',
 'aaron rowand',
 'aaron stephen',
 'aaron talladega',
 'aaugh',
 'aaugh sun',
 'aba',
 'aba foundation',
 'aba sessions',
 'aba sus',
 'aba therapy',
 'aba well',
 'aback',
 'aback bit',
 'aback take',
 'aballaby',
 'aballaby nbsp',
 'abandon',
 'abandon days',
 'abandon life',
 'abandon little',
 'abandon may',
 'abandoned',
 'abandoned adults',
 'abandoned although',
 'abandoned attacking',
 'abandoning',
 'abandoning isreal',
 'abba',
 'abba gold',
 'abba tune',
 'abbey',
 'abbey jay',
 'abbey trying',
 'abbreviate',
 'abbreviate fun',
 'abbreviation',
 'abbreviation next',
 'abby',
 'abby hey',
 'abc',
 'abc family',
 'abc keeping',
 'abc last',
 'abc news',
 'abc nightline',
 'abcnews',
 'abcnews com',
 'abcnews go',
 'abdicate',
 'abdicate overthrown',
 'abdomen',
 'abdomen hips',
 'abdomen thighs',
 'abdominal',
 'abdominal area',
 'abduction',
 'abduction tape',
 'abductor',
 'abductor cooperative',
 'abercrombie',
 'abercrombie boxers',
 'abercrombie fitch',
 'abercrombie sells',
 'aberrant',
 'aberrant really',
 'aberration',
 'aberration got',
 'abhor',
 'abhor middle',
 'abi',
 'abi station',
 'abide',
 'abide geneva',
 'abided',
 'abided international',
 'abiding',
 'abiding christian',
 'abidjan',
 'abidjan ivory',
 'abilities',
 'abilities increased',
 'abilities limited',
 'abilities notary',
 'ability',
 'ability almost',
 'ability asked',
 'ability believe',
 'ability charm',
 'ability collect',
 'ability develop',
 'ability edit',
 'ability even',
 'ability film',
 'ability function',
 'ability get',
 'ability hold',
 'ability incorporate',
 'ability jump',
 'ability keep',
 'ability make',
 'ability outrun',
 'ability really',
 'ability see',
 'ability sit',
 'ability take',
 'ability talking',
 'ability tap',
 'abit',
 'abit nervous',
 'abject',
 'abject horror',
 'ablaze',
 'ablaze lot',
 'able',
 'able actually',
 'able answer',
 'able anything',
 'able appreciate',
 'able attend',
 'able avoid',
 'able buy',
 'able catch',
 'able click',
 'able come',
 'able communicate',
 'able conduct',
 'able confirm',
 'able conjure',
 'able control',
 'able convert',
 'able copy',
 'able create',
 'able define',
 'able deliver',
 'able depend',
 'able develop',
 'able distinguish',
 'able dominate',
 'able dont',
 'able download',
 'able drink',
 'able drive',
 'able engage',
 'able entertain',
 'able establish',
 'able express',
 'able face',
 'able figure',
 'able find',
 'able fully',
 'able fun',
 'able function',
 'able get',
 'able glimpse',
 'able go',
 'able golf',
 'able handle',
 'able hang',
 'able help',
 'able hide',
 'able hit',
 'able increase',
 'able influence',
 'able inundate',
 'able join',
 'able kick',
 'able learn',
 'able least',
 'able leave',
 'able live',
 'able locate',
 'able look',
 'able mail',
 'able make',
 'able maneuver',
 'able move',
 'able much',
 'able offer',
 'able oh',
 'able operate',
 'able overcome',
 'able patch',
 'able play',
 'able post',
 'able profit',
 'able pull',
 'able put',
 'able raed',
 'able reach',
 'able read',
 'able recognise',
 'able rectify',
 'able redefine',
 'able reduce',
 'able replace',
 'able resist',
 'able ride',
 'able said',
 'able see',
 'able separate',
 'able shim',
 'able shut',
 'able sing',
 'able sleep',
 'able soak',
 'able speak',
 'able stand',
 'able stay',
 'able still',
 'able stroll',
 'able supposed',
 'able take',
 'able tell',
 'able things',
 'able transfer',
 'able travel',
 'able type',
 'able update',
 'able urllink',
 'able use',
 'able utilize',
 'able vote',
 'able walk',
 'able watch',
 'able withstand',
 'able work',
 'able yell',
 'ablity',
 'ablity teleport',
 'abm',
 'abm treaty',
 'abnormal',
 'abnormal positions',
 'abode',
 'abode wahoo',
 'abolition',
 'abolition primary',
 'aboout',
 'aboout clarinet',
 'abortion',
 'abortion akin',
 'abortion environment',
 'abortion problem',
 'abortion sex',
 'abortions',
 'abortions already',
 'abortions void',
 'abound',
 'abound like',
 'abounds',
 'abounds sunshine',
 'abouta',
 'abouta shop',
 'abraham',
 'abraham lincoln',
 'abrasive',
 'abrasive complicated',
 'abreast',
 'abreast current',
 'abreast going',
 'abreu',
 'abreu phi',
 'abri',
 'abri el',
 'abridgement',
 'abridgement actual',
 'abridgement finished',
 'abridgement released',
 'abridging',
 'abridging freedom',
 'abrio',
 'abrio la',
 'abroad',
 'abroad falls',
 'abroad friends',
 'abroad integrity',
 'abroad may',
 'abrupt',
 'abrupt click',
 'abrupt end',
 'abrupt times',
 'abs',
 'abs favorite',
 'abs maybe',
 'abs spy',
 'abscess',
 'abscess bank',
 'absence',
 'absence also',
 'absence always',
 'absence benefit',
 'absence democratic',
 'absence know',
 'absence makes',
 'absence reproached',
 'absence spam',
 'absence specific',
 'absent',
 'absent better',
 'absent bullies',
 'absent could',
 'absent however',
 'absent parent',
 'absent show',
 'absent vacuum',
 'absentee',
 'absentee ballots',
 'absentee father',
 'absoluetley',
 'absoluetley nothing',
 'absolulty',
 'absolulty clue',
 'absolute',
 'absolute applies',
 'absolute declarative',
 'absolute hoot',
 'absolute moxie',
 'absolute must',
 'absolute opposition',
 'absolute resources',
 'absolute shite',
 'absolute whooped',
 'absolutely',
 'absolutely abhor',
 'absolutely agree',
 'absolutely awesome',
 'absolutely beautiful',
 'absolutely benefit',
 'absolutely bubbles',
 'absolutely called',
 'absolutely confidence',
 'absolutely convinced',
 'absolutely could',
 'absolutely desire',
 'absolutely disrespectful',
 'absolutely english',
 'absolutely everything',
 'absolutely fenomenal',
 'absolutely gorgeous',
 'absolutely harmless',
 'absolutely hates',
 'absolutely hilarious',
 'absolutely huge',
 'absolutely idea',
 'absolutely immediate',
 'absolutely impossible',
 'absolutely love',
 'absolutely loveable',
 'absolutely luck',
 'absolutely must',
 'absolutely necessary',
 'absolutely nice',
 'absolutely nothing',
 'absolutely offense',
 'absolutely perfect',
 'absolutely pissed',
 'absolutely positively',
 'absolutely refused',
 'absolutely relaxing',
 'absolutely ridiculous',
 'absolutely right',
 'absolutely sense',
 'absolutely serene',
 'absolutely service',
 'absolutely sign',
 'absolutely struck',
 'absolutely stunning',
 'absolutely stupid',
 'absolutely think',
 'absolutely traumatized',
 'absolutely ucalled',
 'absolutely use',
 'absolutely want',
 'absolutes',
 'absolutes always',
 'absolutes none',
 'absolutes objective',
 'absolutes peace',
 'absolutes seems',
 'absolutes wary',
 'absolution',
 'absolution others',
 'absolutist',
 'absolutist taste',
 'absolutistic',
 'absolutley',
 'absolutley random',
 'absolutly',
 'absolutly courage',
 'absolutly crazy',
 'absolutly fucking',
 'absolutly nothing',
 'absolutly pointless',
 'absolutly soaked',
 'absolving',
 'absolving child',
 'absolving parents',
 'absorb',
 'absorb could',
 'absorb cover',
 'absorb unique',
 'absorbed',
 'absorbed girl',
 'absorbed give',
 'absorbed thoughts',
 'absorbent',
 'absorbent cacophony',
 'absorbing',
 'absorbing panels',
 'absorption',
 'absorption want',
 'absoultly',
 'absoultly love',
 'abstain',
 'abstain go',
 'abstained',
 'abstained instead',
 'abstract',
 'abstract art',
 'abstract proposition',
 'abstract tonight',
 'abstract true',
 'abstraction',
 'abstraction philosophical',
 'abstraction wonderful',
 'absurd',
 'absurd also',
 'absurd naive',
 'absurdities',
 'absurdities like',
 'abt',
 'abt cleaniness',
 'abt money',
 'abt plus',
 'abt since',
 'abt wat',
 'abt wrong',
 'abu',
 'abu dhabi',
 'abu ghraib',
 'aburrici',
 'aburrici nisiquiera',
 'abuse',
 'abuse abu',
 'abuse children',
 'abuse health',
 'abuse ioc',
 'abuse know',
 'abuse saw',
 'abuse unrealistic',
 'abuse want',
 'abused',
 'abused oh',
 'abused serial',
 'abused thompson',
 'abused urllink',
 'abusing',
 'abusing eight',
 'abusive',
 'abusive childhood',
 'abusive merit',
 'abyss',
 'abyss comapred',
 'abyss really',
 'ac',
 'ac goes',
 'ac later',
 'ac pre',
 'ac unit',
 'ac va',
 'aca',
 'aca nos',
 'aca tonces',
 'academic',
 'academic level',
 'academics',
 'academics adaptive',
 'academics really',
 'academy',
 'academy award',
 'academy awards',
 'academy cannes',
 'academy college',
 'academy graduation',
 'acamedic',
 'acamedic gpa',
 'accelerating',
 'accelerating convo',
 'accent',
 'accent apply',
 'accent caller',
 'accent everything',
 'accent gaadnaa',
 'accent knows',
 'accent lol',
 'accent nephews',
 'accent say',
 'accent sentece',
 'accent speak',
 'accent speaks',
 'accent still',
 'accent talking',
 'accent uh',
 'accent way',
 'accented',
 'accented etc',
 'accented mildly',
 'accents',
 'accents drawls',
 'accents french',
 'accents good',
 'accents heh',
 'accents would',
 'accept',
 'accept another',
 'accept application',
 'accept changed',
 'accept choices',
 'accept comes',
 'accept criticism',
 'accept delivery',
 'accept deserve',
 'accept especially',
 'accept exactly',
 'accept fact',
 'accept find',
 'accept higher',
 'accept individual',
 'accept jimi',
 'accept known',
 'accept monumental',
 'accept move',
 'accept nomination',
 'accept really',
 'accept reflective',
 'accept respect',
 'accept saw',
 'accept speaking',
 'accept suppose',
 'accept thinking',
 'accept truth',
 'accept webcam',
 'accept wholeheartedly',
 'acceptability',
 'acceptability unacceptability',
 'acceptable',
 'acceptable assuming',
 'acceptable indeed',
 'acceptable level',
 'acceptable long',
 'acceptable practice',
 'acceptable tell',
 'acceptable topics',
 'acceptable vague',
 'acceptable went',
 'acceptance',
 'acceptance possibility',
 'acceptance speech',
 'acceptance things',
 'acceptance thought',
 'accepted',
 'accepted backed',
 'accepted case',
 'accepted english',
 'accepted fiction',
 'accepted flaw',
 'accepted freedom',
 'accepted long',
 'accepted offer',
 'accepted one',
 'accepted policy',
 'accepted prime',
 'accepted scientists',
 'accepted think',
 'accepted unconditionally',
 'accepting',
 'accepting anything',
 'accepting complements',
 'accepting fact',
 'accepting nice',
 'accepting power',
 'accepts',
 'accepts genius',
 'accepts god',
 'access',
 'access archives',
 'access blog',
 'access broadway',
 'access edit',
 'access eugene',
 'access favorite',
 'access flight',
 'access get',
 'access point',
 'access points',
 'access pot',
 'access power',
 'access prisoners',
 'access server',
 'access set',
 'access show',
 'access swaying',
 'accessibility',
 'accessibility web',
 'accessible',
 'accessible americans',
 'accessible friend',
 'accessories',
 'accessories etc',
 'accf',
 'accf applause',
 'accident',
 'accident accident',
 'accident always',
 'accident anyways',
 'accident blonde',
 'accident cars',
 'accident coupla',
 'accident drunk',
 'accident dying',
 'accident east',
 'accident electrical',
 'accident everything',
 'accident fatalities',
 'accident foot',
 'accident honest',
 'accident keep',
 'accident last',
 'accident mistake',
 'accident noticed',
 'accident number',
 'accident obviously',
 'accident really',
 'accident shot',
 'accident tester',
 'accident watched',
 'accident way',
 'accident whenever',
 'accidental',
 'accidental shooting',
 'accidentally',
 'accidentally caused',
 'accidentally chose',
 'accidentally destroy',
 'accidentally erased',
 'accidentally hit',
 'accidentally shot',
 'accidentally slipped',
 'accidentally willow',
 'accidently',
 'accidently blew',
 'accidently insulting',
 'accidents',
 'accidents near',
 'accidents point',
 'accidents tickets',
 'acclaimed',
 'acclaimed yet',
 'acclimate',
 'acclimate shelter',
 'acclimated',
 'acclimated culture',
 'accolades',
 'accolades jennifer',
 'accomack',
 'accomack danville',
 'accommodate',
 'accommodate cough',
 'accommodation',
 'accommodation words',
 'accommodations',
 'accommodations production',
 'accomodate',
 'accomodate false',
 'accomodation',
 'accomodation air',
 'accomodation already',
 'accompanied',
 'accompanied cheesy',
 'accompanied extraordinary',
 'accompanied friend',
 'accompanied good',
 'accompanied light',
 'accompanied taylor',
 'accompany',
 'accompany eerie',
 'accompany go',
 'accompany meal',
 'accompany new',
 'accompanying',
 'accompanying entourage',
 'accompanying nbsp',
 'accompanying serious',
 'accomplices',
 'accomplices taking',
 'accomplish',
 'accomplish anything',
 'accomplish grace',
 'accomplish stress',
 'accomplish task',
 'accomplish think',
 'accomplish work',
 'accomplished',
 'accomplished certainly',
 'accomplished country',
 'accomplished inception',
 'accomplished little',
 'accomplished nothing',
 'accomplished set',
 'accomplished smallest',
 'accomplished speech',
 'accomplished spooning',
 'accomplished thing',
 'accomplished think',
 'accomplished thus',
 'accomplished track',
 'accomplished truly',
 'accomplished trust',
 'accomplishes',
 'accomplishes nothing',
 'accomplishing',
 'accomplishing look',
 'accomplishment',
 'accomplishment every',
 'accomplishment following',
 'accomplishment susan',
 'accomplishments',
 'accomplishments exploded',
 'accomplishments governor',
 'accomplishments president',
 'accomplishments provide',
 'accomplishments results',
 'accomplishments telling',
 'accomplishments want',
 'accord',
 'accord air',
 'accord going',
 'accord making',
 'according',
 'according abc',
 'according amount',
 'according apple',
 'according beacon',
 'according beat',
 'according bigger',
 'according black',
 'according book',
 'according camp',
 'according castillion',
 'according cbs',
 'according company',
 'according competent',
 'according dad',
 'according deity',
 'according effects',
 'according einstein',
 'according enemies',
 'according enough',
 'according every',
 'according father',
 'according federal',
 'according friend',
 'according government',
 'according information',
 'according isi',
 'according jeffrey',
 'according joint',
 'according leia',
 'according luc',
 'according moore',
 'according new',
 'according newly',
 'according nurse',
 'according one',
 'according phil',
 'according plan',
 'according postal',
 'according prophecy',
 'according psychiatrist',
 'according psychologist',
 'according recently',
 'according red',
 'according rolling',
 'according schedule',
 'according sorta',
 'according spoilers',
 'according sun',
 'according symbol',
 'according tastes',
 'according tenable',
 'according time',
 'according tune',
 'according urllink',
 'according westphal',
 'accordingly',
 'accordingly constitutes',
 'accordingly court',
 'accordingly heck',
 'accosted',
 'accosted boy',
 'accosted man',
 'account',
 'account almost',
 'account americas',
 'account answer',
 'account anyways',
 'account awhile',
 'account bank',
 'account block',
 'account dan',
 'account day',
 'account days',
 'account dictionary',
 'account earn',
 'account eating',
 'account face',
 'account forwarded',
 'account good',
 'account grand',
 'account jason',
 'account karma',
 'account last',
 'account local',
 'account logon',
 'account make',
 'account means',
 'account minutes',
 'account need',
 'account nifty',
 'account old',
 'account pic',
 'account sat',
 'account savings',
 'account send',
 'account since',
 'account supervisors',
 'account taxes',
 'account though',
 'account us',
 'account use',
 'account week',
 'account www',
 'account years',
 'accountability',
 'accountability effect',
 'accountability parents',
 'accountable',
 'accountable distortion',
 'accountable every',
 'accountable http',
 'accountant',
 'accountant paper',
 'accountant son',
 'accountant taxpayer',
 'accountants',
 'accountants tidying',
 'accounted',
 'accounted grieve',
 'accounted taxes',
 'accounted thanks',
 'accounting',
 'accounting software',
 'accounts',
 'accounts cds',
 'accounts deaths',
 'accounts gets',
 'accounts going',
 'accounts history',
 'accounts supplement',
 'accounts th',
 'accounts various',
 'accoustic',
 'accoustic life',
 'accra',
 'accra ghana',
 'accross',
 'accross floor',
 'accrue',
 'accrue taxes',
 'accruing',
 'accruing lot',
 'accumulated',
 'accumulated credit',
 'accumulated wasted',
 'accumulating',
 'accumulating inches',
 'accuracy',
 'accuracy depicting',
 'accuracy information',
 'accuracy mean',
 'accuracy one',
 'accurate',
 'accurate barrel',
 'accurate definition',
 'accurate description',
 'accurate far',
 'accurate find',
 'accurate gun',
 'accurate matter',
 'accurate numbers',
 'accurate relevant',
 'accurate replied',
 'accurate representation',
 'accurate say',
 'accurate suddenly',
 'accurately',
 'accurately carbs',
 'accurately pathetic',
 'accurately topic',
 'accursed',
 'accursed haunting',
 'accusation',
 'accusation better',
 'accusation blair',
 'accusations',
 'accusations made',
 'accused',
 'accused believe',
 'accused huh',
 'accused julius',
 'accused reverse',
 'accused spoiler',
 'accused thousands',
 'accusers',
 'accusers generally',
 'accusing',
 'accusing mr',
 'accustomed',
 'accustomed continue',
 'ace',
 'ace bandages',
 'ace enders',
 'ace way',
 'acepto',
 'acepto se',
 'acerco',
 'acerco la',
 'aces',
 'ache',
 'ache ache',
 'ache asthanga',
 'ache bled',
 'ache body',
 'ache concentrated',
 'ache get',
 'ache goes',
 'ache one',
 'ache pain',
 'ache really',
 'ache tell',
 'ached',
 'ached weeks',
 'acheive',
 'acheive aims',
 'acheive urllink',
 'acheived',
 'acheived time',
 'acheivements',
 'acheivements past',
 'aches',
 'aches early',
 'aches expect',
 'aches horrible',
 'aches nausea',
 'aches smell',
 'aches want',
 'achieve',
 ...]

In [83]:
dtm_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [85]:
dtm_train.shape

(3500, 238234)

In [89]:
df.head()

,text,labels
0,info found pages mb pdf files wait untill team...,"[male, 15, Student, Leo]"
1,team members drewes van der laag urllink mail ...,"[male, 15, Student, Leo]"
2,het kader van kernfusie op aarde maak je eigen...,"[male, 15, Student, Leo]"
3,testing testing,"[male, 15, Student, Leo]"
4,thanks yahoo toolbar capture urls popups means...,"[male, 33, InvestmentBanking, Aquarius]"

In [90]:
df.labels.values

array([list(['male', '15', 'Student', 'Leo']),
       list(['male', '15', 'Student', 'Leo']),
       list(['male', '15', 'Student', 'Leo']), ...,
       list(['female', '17', 'indUnk', 'Scorpio']),
       list(['female', '17', 'indUnk', 'Scorpio']),
       list(['female', '17', 'indUnk', 'Scorpio'])], dtype=object)

In [92]:
label_counts = dict()

for labels in df.labels.values:
    for label in labels:
        if label in label_counts:
            label_counts[label] += 1
        else:
            label_counts[label] = 1

In [93]:
label_counts

{'male': 3294,
 '15': 339,
 'Student': 569,
 'Leo': 190,
 '33': 101,
 'InvestmentBanking': 70,
 'Aquarius': 329,
 'female': 1706,
 '14': 170,
 'indUnk': 1381,
 'Aries': 2483,
 '25': 268,
 'Capricorn': 84,
 '17': 331,
 'Gemini': 86,
 '23': 137,
 'Non-Profit': 47,
 'Cancer': 94,
 'Banking': 16,
 '37': 19,
 'Sagittarius': 704,
 '26': 96,
 '24': 353,
 'Scorpio': 408,
 '27': 86,
 'Education': 118,
 '45': 14,
 'Engineering': 119,
 'Libra': 414,
 'Science': 33,
 '34': 540,
 '41': 14,
 'Communications-Media': 61,
 'BusinessServices': 87,
 'Sports-Recreation': 75,
 'Virgo': 41,
 'Taurus': 100,
 'Arts': 31,
 'Pisces': 67,
 '44': 3,
 '16': 67,
 'Internet': 20,
 'Museums-Libraries': 2,
 'Accounting': 2,
 '39': 79,
 '35': 2307,
 'Technology': 2332,
 '36': 60,
 'Law': 3,
 '46': 7,
 'Consulting': 16,
 'Automotive': 14,
 '42': 9,
 'Religion': 4}

In [96]:
from sklearn.preprocessing import MultiLabelBinarizer
MLB= MultiLabelBinarizer(classes= sorted(label_counts.keys()))

y_train= MLB.fit_transform(y_train)
y_test= MLB.transform(y_test)

In [97]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(solver='lbfgs')
clf = OneVsRestClassifier(clf)

In [98]:
logreg_model= clf.fit(dtm_train, y_train)

In [99]:
y_pred= logreg_model.predict(dtm_test)

In [100]:
y_pred

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [102]:
pred_inverse= MLB.inverse_transform(y_pred)
y_test_inversed = MLB.inverse_transform(y_test)

In [104]:
from sklearn.metrics import accuracy_score, f1_score, average_precision_score, recall_score

In [105]:
accuracy_score(y_test, y_pred)

0.514

In [108]:
f1_score(y_test, y_pred, average= 'micro' )

0.7287944329509123

In [109]:
average_precision_score(y_test, y_pred, average= 'micro')

0.5662872581616288

In [110]:
recall_score(y_test, y_pred, average= 'micro')

0.6458333333333334

In [113]:
for i in range(0, 5):
    print('Actual:', y_test_inversed[i], '&', 'Predicted:',pred_inverse[i])

Actual: ('35', 'Aries', 'Technology', 'male') & Predicted: ('35', 'Aries', 'Technology', 'male')
Actual: ('16', 'Libra', 'Student', 'female') & Predicted: ('female',)
Actual: ('14', 'Scorpio', 'indUnk', 'male') & Predicted: ('35', 'Aries', 'Technology', 'male')
Actual: ('35', 'Aries', 'Technology', 'male') & Predicted: ('35', 'Aries', 'Technology', 'male')
Actual: ('35', 'Aries', 'Technology', 'male') & Predicted: ('35', 'Aries', 'Technology', 'male')